"""로그인 화면 인식 삭제, 구글 연동 기능 수정

Revision ID: 2fee6f690985
Revises: 5f5a82ef8a58
Create Date: 2026-06-10 14:54:57.250776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fee6f690985'
down_revision: Union[str, Sequence[str], None] = '5f5a82ef8a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
