"""관리자 테이블 추가(admin_accounts, llm_models, admin_audit_logs) 및 user status suspended

Revision ID: 3a6ba87840b6
Revises: 7c1d9e4a2b3f
Create Date: 2026-06-15 15:54:57.330072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3a6ba87840b6'
down_revision: Union[str, Sequence[str], None] = '7c1d9e4a2b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='로그인 ID(이메일).'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='passlib bcrypt 해시.'),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin', name='adminrole'), server_default=sa.text("'admin'"), nullable=False, comment='super_admin 만 관리자 계정·감사 로그 관리 가능.'),
    sa.Column('status', sa.Enum('active', 'disabled', name='adminstatus'), server_default=sa.text("'active'"), nullable=False, comment='활성 | 비활성'),
    sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='refresh 토큰 무효화용. 로그아웃 시 +1.'),
    sa.Column('last_login_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('llm_models',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.Enum('google', 'openai', 'anthropic', name='llmprovider'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='API 식별자. 예: gemini-3.5-flash'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='UI 표시명.'),
    sa.Column('params', sa.JSON(), nullable=True, comment='기본 호출 파라미터(temperature 등).'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='활성 모델 여부. 정확히 1개 행만 true 를 유지한다(교체 시 트랜잭션).'),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False, comment='예: export_keypoints, activate_llm, update_user_status'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='user | exercise | session | llm_model'),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True, comment='필터 조건·변경 전후값 등 부가 정보.'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # users.status ENUM 에 'suspended'(관리자 정지) 추가 — autogenerate 미감지분 수동 보강.
    op.alter_column(
        "users",
        "status",
        existing_type=mysql.ENUM("active", "withdrawn"),
        type_=mysql.ENUM("active", "suspended", "withdrawn"),
        existing_nullable=False,
        existing_server_default=sa.text("'active'"),
        existing_comment="활성 | 탈퇴",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # users.status ENUM 에서 'suspended' 제거 (정지 회원이 없어야 안전).
    op.alter_column(
        "users",
        "status",
        existing_type=mysql.ENUM("active", "suspended", "withdrawn"),
        type_=mysql.ENUM("active", "withdrawn"),
        existing_nullable=False,
        existing_server_default=sa.text("'active'"),
        existing_comment="활성 | 탈퇴",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_audit_logs')
    op.drop_table('llm_models')
    op.drop_table('admin_accounts')
    # ### end Alembic commands ###
