"""init

Revision ID: 5f5a82ef8a58
Revises: 
Create Date: 2026-06-09 08:51:01.498228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5f5a82ef8a58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name_ko', sa.String(length=100), nullable=False, comment='표시 이름(한글).'),
    sa.Column('name_en', sa.String(length=100), nullable=True, comment='표시 이름(영문).'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_video_url', sa.String(length=500), nullable=True, comment='정답(모범) 영상 URL.'),
    sa.Column('exercise_type', sa.Enum('static', 'dynamic', name='exercisetype'), server_default=sa.text("'dynamic'"), nullable=False, comment='정적운동 static | 동적운동 dynamic'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='운동 종목 노출 여부'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='구글에서 받아온 이름이 기본'),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), server_default=sa.text("'user'"), nullable=False, comment='사용자 | 관리자'),
    sa.Column('status', sa.Enum('active', 'withdrawn', name='userstatus'), server_default=sa.text("'active'"), nullable=False, comment='활성 | 탈퇴'),
    sa.Column('withdrawn_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agreements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tos_agreed', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='서비스 이용약관(필수)'),
    sa.Column('privacy_agreed', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='개인정보 수집·이용(필수)'),
    sa.Column('biometric_agreed', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='바이오정보(얼굴) 처리(필수)'),
    sa.Column('marketing_agreed', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='마케팅 수신(선택)'),
    sa.Column('agreed_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('face_embeddings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('embedding', sa.VARBINARY(length=2048), nullable=False, comment='개인정보. 직렬화된 임베딩 벡터(가능하면 애플리케이션 단에서 암호화).'),
    sa.Column('model_version', sa.String(length=50), nullable=False, comment='임베딩 모델 버전. 동일 버전끼리만 비교 유효.'),
    sa.Column('bin_file_url', sa.String(length=255), nullable=True, comment='원본 임베딩/이미지 파일의 오브젝트 스토리지 URL(선택).'),
    sa.Column('registered_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='등록날짜'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('social_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='google'),
    sa.Column('provider_uid', sa.String(length=255), nullable=False, comment='개인정보. 소셜 제공자 측 사용자 식별자.'),
    sa.Column('provider_email', sa.String(length=255), nullable=True, comment='개인정보. 소셜 제공자 이메일(없을 수 있음).'),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_uid', name='uq_provider_uid')
    )
    op.create_table('user_details',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('height', sa.Numeric(precision=4, scale=1), nullable=True, comment='cm (50~250)'),
    sa.Column('weight', sa.Numeric(precision=4, scale=1), nullable=True, comment='kg (20~300)'),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', 'U', name='gender'), nullable=False, comment='남성 | 여성 | 선택 안 함'),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workout_daily_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('session_count', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('total_duration_sec', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('avg_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('best_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', 'stat_date', name='uq_user_exercise_date')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'aborted', name='sessionstatus'), server_default=sa.text("'in_progress'"), nullable=False),
    sa.Column('started_at', mysql.DATETIME(fsp=6), nullable=False, comment='세션 시작 시각(UTC).'),
    sa.Column('ended_at', mysql.DATETIME(fsp=6), nullable=True, comment='세션 종료 시각(UTC). 진행 중이면 NULL.'),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True, comment='0~100점. 완료 시에만 채워짐.'),
    sa.Column('rep_count', mysql.INTEGER(unsigned=True), nullable=True, comment='반복 횟수(횟수 기반 운동).'),
    sa.Column('hold_sec', mysql.INTEGER(unsigned=True), nullable=True, comment='자세 유지 시간(초)(시간 기반 운동).'),
    sa.Column('saved', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='사용자가 영상을 저장했는지 여부.'),
    sa.Column('video_url', sa.String(length=500), nullable=True, comment='개인정보. saved=true일 때 오브젝트 스토리지 URL.'),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_started', 'workout_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='사용자에게 보여줄 자연어 피드백.'),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='feedbackseverity'), server_default=sa.text("'info'"), nullable=False),
    sa.Column('generated_by', sa.Enum('rule', 'llm', name='feedbacksource'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keypoint_frames',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False, comment='세션 내 프레임 인덱스(0부터 시작).'),
    sa.Column('timestamp_ms', mysql.BIGINT(unsigned=True), nullable=False, comment='started_at 기준 경과 밀리초.'),
    sa.Column('keypoints', sa.JSON(), nullable=False, comment='정규화된 관절 키포인트(0~1).'),
    sa.Column('bbox', sa.JSON(), nullable=True, comment='사람 바운딩 박스 [x, y, w, h].'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'frame_index', name='uq_session_frame')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keypoint_frames')
    op.drop_table('feedbacks')
    op.drop_index('idx_user_started', table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_table('workout_daily_stats')
    op.drop_table('user_details')
    op.drop_table('social_accounts')
    op.drop_table('face_embeddings')
    op.drop_table('agreements')
    op.drop_table('users')
    op.drop_table('exercises')
    # ### end Alembic commands ###
