"""face_embeddings embedding 컬럼 VARBINARY(2048)→(1024)

Revision ID: 7a492208e919
Revises: f635702f09ba
Create Date: 2026-06-15 11:44:46.874702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a492208e919'
down_revision: Union[str, Sequence[str], None] = 'f635702f09ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('face_embeddings', 'embedding',
               existing_type=sa.VARBINARY(length=2048),
               type_=sa.VARBINARY(length=1024),
               comment='개인정보. dlib 128차원 float64 직렬화 (1024 bytes).',
               existing_comment='개인정보. 직렬화된 임베딩 벡터(가능하면 애플리케이션 단에서 암호화).',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('face_embeddings', 'embedding',
               existing_type=sa.VARBINARY(length=1024),
               type_=sa.VARBINARY(length=2048),
               comment='개인정보. 직렬화된 임베딩 벡터(가능하면 애플리케이션 단에서 암호화).',
               existing_comment='개인정보. dlib 128차원 float64 직렬화 (1024 bytes).',
               existing_nullable=False)
    # ### end Alembic commands ###
