"""social_accounts provider_avatar_url 추가

Revision ID: 84a61b4aea76
Revises: 5f5a82ef8a58
Create Date: 2026-06-11 10:44:37.475149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a61b4aea76'
down_revision: Union[str, Sequence[str], None] = '5f5a82ef8a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('provider_avatar_url', sa.String(length=512), nullable=True, comment='개인정보. 소셜 제공자 프로필 사진 URL(없을 수 있음, 로그인 시 갱신).'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'provider_avatar_url')
    # ### end Alembic commands ###
