"""face_embeddings 테이블 제거

Revision ID: 888995dbe4d5
Revises: ad21e2346bed
Create Date: 2026-06-22 14:46:58.255272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '888995dbe4d5'
down_revision: Union[str, Sequence[str], None] = 'ad21e2346bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_embeddings')
    op.alter_column('workout_sessions', 'started_at',
               existing_type=mysql.DATETIME(fsp=6),
               comment='세션 시작 시각(KST).',
               existing_comment='세션 시작 시각(UTC).',
               existing_nullable=False)
    op.alter_column('workout_sessions', 'ended_at',
               existing_type=mysql.DATETIME(fsp=6),
               comment='세션 종료 시각(KST). 진행 중이면 NULL.',
               existing_comment='세션 종료 시각(UTC). 진행 중이면 NULL.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_sessions', 'ended_at',
               existing_type=mysql.DATETIME(fsp=6),
               comment='세션 종료 시각(UTC). 진행 중이면 NULL.',
               existing_comment='세션 종료 시각(KST). 진행 중이면 NULL.',
               existing_nullable=True)
    op.alter_column('workout_sessions', 'started_at',
               existing_type=mysql.DATETIME(fsp=6),
               comment='세션 시작 시각(UTC).',
               existing_comment='세션 시작 시각(KST).',
               existing_nullable=False)
    op.create_table('face_embeddings',
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.VARBINARY(length=1024), nullable=False, comment='개인정보. dlib 128차원 float64 직렬화 (1024 bytes).'),
    sa.Column('model_version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='임베딩 모델 버전. 동일 버전끼리만 비교 유효.'),
    sa.Column('registered_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='등록날짜'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('face_embeddings_ibfk_1')),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
