"""drop biometric_agreed from agreements

Revision ID: af722d07a0af
Revises: 4366353a71d1
Create Date: 2026-06-23 13:34:39.034091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af722d07a0af'
down_revision: Union[str, Sequence[str], None] = '4366353a71d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreements', 'biometric_agreed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('biometric_agreed', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='바이오정보(얼굴) 처리(필수)'))
    # ### end Alembic commands ###
