"""workout_sessions에 json_url 컬럼 추가

Revision ID: c4ac243616fb
Revises: ad21e2346bed
Create Date: 2026-06-22 16:02:00.785372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4ac243616fb'
down_revision: Union[str, Sequence[str], None] = 'ad21e2346bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sessions', sa.Column('json_url', sa.String(length=500), nullable=True, comment='포즈 추정 결과 JSON 파일 경로.'))
    op.alter_column('workout_sessions', 'started_at',
               existing_type=mysql.DATETIME(fsp=6),
               comment='세션 시작 시각(KST).',
               existing_comment='세션 시작 시각(UTC).',
               existing_nullable=False)
    op.alter_column('workout_sessions', 'ended_at',
               existing_type=mysql.DATETIME(fsp=6),
               comment='세션 종료 시각(KST). 진행 중이면 NULL.',
               existing_comment='세션 종료 시각(UTC). 진행 중이면 NULL.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_sessions', 'ended_at',
               existing_type=mysql.DATETIME(fsp=6),
               comment='세션 종료 시각(UTC). 진행 중이면 NULL.',
               existing_comment='세션 종료 시각(KST). 진행 중이면 NULL.',
               existing_nullable=True)
    op.alter_column('workout_sessions', 'started_at',
               existing_type=mysql.DATETIME(fsp=6),
               comment='세션 시작 시각(UTC).',
               existing_comment='세션 시작 시각(KST).',
               existing_nullable=False)
    op.drop_column('workout_sessions', 'json_url')
    # ### end Alembic commands ###
