"""face_embeddings에서 bin_file_url 컬럼 제거

Revision ID: f635702f09ba
Revises: 7c1d9e4a2b3f
Create Date: 2026-06-15 11:00:52.640543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f635702f09ba'
down_revision: Union[str, Sequence[str], None] = '7c1d9e4a2b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_embeddings', 'bin_file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_embeddings', sa.Column('bin_file_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='원본 임베딩/이미지 파일의 오브젝트 스토리지 URL(선택).'))
    # ### end Alembic commands ###
